<?php $_info = $this->getInfo(); ?>
<?php $pixInformation = $this->getPaymentInfo(); ?>
<?php $url_store =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>
<?php $imageIcon = $url_store . 'media/mageshop/pagarme/images/logo_pagarme.svg'; ?>

<div class="box-pagarme">
    <div class="banner" style="width: 100%;
        max-width: 245px;height: 60px;
        background-size: 200px;
        background-repeat: no-repeat;
        background-image: url('<?php echo $imageIcon ?>');"></div>
    <h2><?php echo $this->__('Payment Information:') ?></h2>
    <?php if ($pixInformation && isset($pixInformation['charges'])) : ?>
        <?php foreach ($pixInformation['charges'] as $charge) : ?>
            <table class="payment-info-table">
                <tr>
                    <td><strong><?php echo $this->__('Transaction ID:') ?></strong></td>
                    <td><?php echo $this->__($charge["last_transaction"]['id']) ?></td>
                </tr>
                <tr>
                    <td><strong><?php echo $this->__('Provider TID:') ?></strong></td>
                    <td><?php echo $this->__($charge["last_transaction"]['pix_provider_tid']) ?></td>
                </tr>
                <tr>
                    <td><strong><?php echo $this->__('Status:') ?></strong></td>
                    <td><?php echo $this->__(MageShop_PagarMe_Model_System_Config_Transaction_Status::convertStatus($charge["last_transaction"]['status'])) ?></td>
                </tr>
                <tr>
                    <td><strong><?php echo $this->__('Amount:') ?></strong></td>
                    <td><?php echo $this->__($charge["last_transaction"]['amount']) ?></td>
                </tr>
                <tr>
                    <td><strong><?php echo $this->__('Expires at:') ?></strong></td>
                    <td><?php echo $this->__($charge["last_transaction"]['expires_at']) ?></td>
                </tr>
                <tr>
                    <td><strong><?php echo $this->__('Created at:') ?></strong></td>
                    <td><?php echo $this->__($charge["last_transaction"]['created_at']) ?></td>
                </tr>
                <tr>
                    <td><strong><?php echo $this->__('Updated at:') ?></strong></td>
                    <td><?php echo $this->__($charge["last_transaction"]['updated_at']) ?></td>
                </tr>
                <?php if ($charge["last_transaction"]['status'] == MageShop_PagarMe_Model_System_Config_Transaction_Status::WAITING_PAYMENT) : ?>
                    <tr>
                        <td><strong><?php echo $this->__('QrCode:') ?></strong></td>
                        <td><a href="<?php echo $this->__($charge["last_transaction"]['qr_code_url']) ?>"><?php echo $this->__($charge["last_transaction"]['qr_code_url']) ?></a></td>
                    </tr>
                <?php endif; ?>
            </table>
        <?php endforeach; ?>

    <?php endif; ?>
    <button type="button" onclick="actionLocation('<?php echo $this->getUpdateOrderUrl($_info->getOrder()->getId(), $_info->getOrder()->getPayment()->getPagarmeOrderId()) ?>'); Element.show('loading-mask')"><?= $this->__('Forçar atualização do pedido') ?></button>
</div>
<div style="clear:both; margin-bottom: 20px"></div>

<style>
    .box-pix ul {
        list-style-type: none;
        padding: 0;
        margin: 0;
    }

    .box-pix ul li {
        padding: 10px;
        border-bottom: 1px solid #ddd;
    }

    .box-pix ul li:last-child {
        border-bottom: none;
    }

    .box-pix ul li strong {
        font-weight: bold;
        color: #65a300;
    }

    .box-pix ul li img {
        display: block;
        max-width: 100%;
        margin-top: 10px;
        border-radius: 5px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }
</style>
<script>
    function actionLocation(url) {
        Element.show('loading-mask');
        window.location.href = url;
    }
</script>