<?php
$_helper = Mage::helper('mageshop_pagarme');
$_transaction = $this->getTransacao();

// Decodifica a mensagem de retorno JSON
$returnMessageJson = json_decode($_transaction->getReturnMessage(), true);
$returnMessagePretty = json_encode($returnMessageJson, JSON_PRETTY_PRINT);
?>
<?php if ($this->hasTransacao()) : ?>
<div class="box-left">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo $this->escapeHtml($_helper->__('Transaction Details')) ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tbody>
                    <tr>
                        <td class="label"><label><?php echo $this->escapeHtml($_helper->__('Transaction Date:')) ?></label></td>
                        <td class="value"><strong><?php echo $this->formatDate($_transaction->getCreatedDate(), 'medium', true) ?></strong></td>
                    </tr>
                    <?php if ($this->hasOrder()) : ?>
                    <tr>
                        <td class="label"><label><?php echo $this->escapeHtml($_helper->__('Order ID:')) ?></label></td>
                        <td class="value"><strong><?php echo $this->escapeHtml($this->getOrder()->getRealOrderId()) ?></strong></td>
                    </tr>
                    <?php endif; ?>
                    <tr>
                        <td class="label"><label><?php echo $this->escapeHtml($_helper->__('Transaction Status:')) ?></label></td>
                        <td class="value"><strong><?php echo $this->escapeHtml($this->getStatusDescription()) ?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo $this->escapeHtml($_helper->__('Charge ID:')) ?></label></td>
                        <td class="value"><strong><?php echo $this->escapeHtml($_transaction->getChargeId()) ?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo $this->escapeHtml($_helper->__('Payment Method:')) ?></label></td>
                        <td class="value"><strong><?php echo $this->escapeHtml($_transaction->getPaymentMethod()) ?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo $this->escapeHtml($_helper->__('Capture Amount:')) ?></label></td>
                        <td class="value"><strong><?php echo $this->escapeHtml($this->convertBr($_transaction->getCaptureAmount())) ?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo $this->escapeHtml($_helper->__('Chargeback Amount:')) ?></label></td>
                        <td class="value"><strong><?php echo $this->escapeHtml($this->convertBr($_transaction->getChargebackAmount())) ?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo $this->escapeHtml($_helper->__('TID:')) ?></label></td>
                        <td class="value"><strong><?php echo $this->escapeHtml($_transaction->getTid()) ?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo $this->escapeHtml($_helper->__('Charge:')) ?></label></td>
                        <td class="value"><pre><?php echo $this->escapeHtml($returnMessagePretty) ?></pre></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php endif; ?>

<?php if ($this->hasFooterButtons()) : ?>
<div class="content-footer">
    <p class="form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
</div>
<?php endif; ?>